runner:
  total_steps: 100000
  gradient_clipping: 1
  gradient_accumulate_steps: 16

  log_step: 10
  eval_step: 250
  save_step: 250
  max_keep: 1
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: AdamW
  lr: 2.0e-4

# comment the whole scheduler config block
# to disable learning rate scheduling
scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 1400

downstream_expert:
  datarc:
    session: Session4
    pre_load: True
    train_batch_size: 4
    eval_batch_size: 4
    num_workers: 12
    valid_ratio: 0.1

  modelrc:
    input_dim: 40
    hidden_dim: 80
    kernel_size: 5
    padding: 2
    pooling: 5
    dropout: 0.4
