runner: {}

downstream_expert:
  # Leave it empty to max out performance
  max_workers:

  # Dimension-wise normalize SSL representations
  feature_normalization: True

  # Specify the index of silence frame to be removed or leave it empty
  silence_frame:

  datarc:
    dataset_root: /home/leo/d/datasets/quesst14Database
    num_workers: 8
    batch_size: 1

  dtwrc:
    # Any metric defined by scipy.spatial.distance.cdist, e.g.
    #  - "cosine"
    #  - "cityblock"
    #  - "euclidean"
    #
    # Or some specific designed distance metrics:
    #  - "cosine_exp"
    #  - "cosine_neg_log"
    dist_method: "cosine_exp"

    # Normalize each row of distance matrix
    minmax_norm: True

    # Any StepPattern in dtw-python, e.g.
    #  - "symmetric1"
    #  - "symmetric2" (default in dtw-python)
    #  - "asymmetric"
    step_pattern: "asymmetric"

    # Find open-ended alignment, namely, subsequence DTW, only works with asymmetric as StepPattern
    subsequence: True
