name: Deploy documentation

on:
  push:
    branches:
      - main

jobs:
  deploy-doc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Create virtual environment
        run: |
          python3 -m venv "$HOME/s3prl_env"
          echo "$HOME/s3prl_env/bin" >> $GITHUB_PATH

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsndfile1-dev sox

      - name: Upgrade pip and wheel
        run: pip3 install --upgrade pip wheel

      - name: install S3PRL
        run: |
          pip install -e ".[dev]"

      # - name: Setup upterm sessions
      #   uses: lhotari/action-upterm@v1

      - name: Build doc
        run: |
          cd docs/
          ./rebuild_docs.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html

